## AeroFlu Configuration ##

# Simulation parameters
timeSteps = 10000
numInfections = 1
initialVirions = 1000
neighRadius = 1.5
ranSeed = 12345

# Cell parameters
incubationPeriod = 480
expressingPeriod = 900
virionProduction = 1.1
virionDiffusion = 0.15
virionClearance = 0.004
