## AeroFlu Configuration ##

# Simulation parameters
timeSteps = 10000
numInfections = 1000
initialVirions = 1000
neighRadius = 6.0
ranSeed = 12345

# Cell parameters
incubationPeriod = 480
expressingPeriod = 900
virionProduction = 1.0
virionDiffusion = 0.02
virionClearance = 0.004
IFNproduction = 25.0
IFNdiffusion = 0.04
IFNclearance = 0.008
