## AeroFlu Configuration ##

# Simulation parameters
timeSteps = 10000
numInfections = 20
initialVirions = 1000
neighRadius = 8.0
ranSeed = 12345

# Cell parameters
incubationPeriod = 480
expressingPeriod = 900
virionProduction = 1.1
virionDiffusion = 0.20
virionClearance = 0.004
IFNproduction = 0.0
IFNdiffusion = 0.0
IFNclearance = 0.000
