## AeroFlu Configuration ##
## Step time is 1 minute, so 1440 steps correspond to 1 day.

# Simulation parameters
timeSteps = 14400
numInfections = 1
initialVirions = 100
neighRadius = 6.0
numReplicates = 100
ranSeed = 12345

# Cell parameters
infectingPeriod = 1800
nonPermissiveProbability = 0.3
IFNcellProbability = 0.3

# Diffusion parameters
virionDiffusion = 0.001
IFNdiffusion = 0.2

virionClearance = 0.0115
IFNclearance = 0.005760

# Printing options
printSnapshots = 0
snapshotInterval = 60
measureInterval = 60