## AeroFlu Configuration ##
## Step time is 1 minute, so 1440 steps correspond to 1 day.

# Simulation parameters
timeSteps = 4000
numInfections = 1
initialVirions = 0
neighRadius = 1.2
ranSeed = 12345

# Cell parameters
infectingPeriod = 3000
nonPermissiveProbability = 0.3
IFNcellProbability = 0.3

# Diffusion parameters
virionDiffusion = 0.0
virionClearance = 0.0

IFNdiffusion = 0.0
IFNclearance = 0.0

# Printing options
printSnapshots = 0
snapshotInterval = 100

measureInterval = 100