## AeroFlu Configuration ##

# Simulation parameters
timeSteps = 4000
numInfections = 1
initialVirions = 100
neighRadius = 1.2
ranSeed = 12345

# Cell parameters
incubationPeriod = 480
expressingPeriod = 900

nonPermissiveProbability = 0.3

virionDiffusion = 0.01
virionClearance = 0.004

IFNcellProbability = 0.3
IFNdiffusion = 0.05
IFNclearance = 0.005776
