## AeroFlu Configuration ##
## Step time is 1 minute, so 1440 steps correspond to 1 day.

# Simulation parameters
timeSteps = 8000
numInfections = 1
initialVirions = 0
neighRadius = 3
ranSeed = 12345

# Cell parameters
infectingPeriod = 1800
nonPermissiveProbability = 0.3
IFNcellProbability = 0.3

# Diffusion parameters
virionDiffusion = 0.01
virionClearance = 0.005

IFNdiffusion = 0.1
IFNclearance = 0.005

# Printing options
printSnapshots = 1
snapshotInterval = 100

measureInterval = 100